### ISSUE TITLE
Предложения по компонентам

### ISSUE THREAD

**Issue by AnatolyBur** [garpixcms/garpix_page#27]
Нужна возможность фильтровать компоненты.
Так же нужно придумать систему кэширование компонентов и страниц. Нужна возможность из админ панеле скидывать кэш компонентов, страниц, всего сайта. При изменение страниц/компонента кэш должен обновляться частично

**Comment by griviala** [comment]
Постепенно сделано в разных версиях. Полностью готово к версии 2.39.0
