### ISSUE TITLE
Обработка битых страниц

### ISSUE THREAD

**Issue by Alshevsky** [garpixcms/garpix_page#37]
Если вдруг в бд создается битая страница, то в админке при попытке перейти в блок со списком страниц падает ошибка, было бы круто добавить обработку, которая показывает из-за какой страницы проблема.

https://github.com/garpixcms/garpix_page/blob/0bb3e0bf0edcda4ba7699b607ef8bc42ca86794b/backend/garpix_page/models/base_page.py#L148

**Comment by griviala** [comment]
Исправлено в https://github.com/garpixcms/garpix_page/pull/39
