### ISSUE TITLE
Ошибка при удалении страницу из любого раздела кроме "PAGES:Структура страниц"

### ISSUE THREAD

**Issue by MarychevGarpix** [garpixcms/garpix_page#5]
```
CantDisableUpdates at /admin/catalog/product/ 
 You can't disable/delay mptt updates on Product, it doesn't contain the mptt fields.
 ```

Шаги воспроизведения ошибки.

0. Напимер мы имеем *CatalogPage* как тип страниц унаследованный от `BasePage`.
```
  class CatalogPage(BasePage):
      ...
```
1. Создать страницу `Категория-1`.
2. Добавить 2ю страницу `Категория-2` и указать в "Родительской странице" - `Категория-1`
3. Удалить страницу `Страница-2` из раздела *CatalogPage*

Но удалить страницу все же есть возможность!
Нужно перейти враздел *PAGES:Структура страниц* и удалить страницу от туда.
Также, пока проблема не будет решена стоит отменить уделние в админке.

```
class CatalogPageAdmin(BasePageAdmin):
    
    ...

    def has_delete_permission(self, request, obj=None) -> bool:
        """
        [TODO] CantDisableUpdates at /admin/catalog/product/:
            You can't disable/delay mptt updates on Product, it doesn't contain the mptt fields.
        """
        return request.path.startswith('/admin/garpix_page/basepage/')
```

![BasePageAndRemoveGIT_BUG-2021-08-30_10-31](https://user-images.githubusercontent.com/86674776/131305733-6ef22e26-f1ad-4c59-b79b-76546862cbbc.png)
![BasePageAndRemoveGIT_BUG--2-2021-08-30_10-31](https://user-images.githubusercontent.com/86674776/131305735-eb9c8601-3cb9-49c4-bcc2-d7d353346fd7.png)
![GIT_BUG--2-2021-08-30_10-31](https://user-images.githubusercontent.com/86674776/131305738-b53fcc09-993b-4fee-90ca-b792707a3e0f.png)

**Comment by crusat** [comment]
Проблема решена другим путем. Теперь есть только Структура страниц.
